// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: balance_service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FiatService_AddBalanceByAdmin_FullMethodName = "/foundationtoken.FiatService/AddBalanceByAdmin"
)

// FiatServiceClient is the client API for FiatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FiatService defines the balance service.
type FiatServiceClient interface {
	AddBalanceByAdmin(ctx context.Context, in *BalanceAdjustmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fiatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFiatServiceClient(cc grpc.ClientConnInterface) FiatServiceClient {
	return &fiatServiceClient{cc}
}

func (c *fiatServiceClient) AddBalanceByAdmin(ctx context.Context, in *BalanceAdjustmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FiatService_AddBalanceByAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FiatServiceServer is the server API for FiatService service.
// All implementations must embed UnimplementedFiatServiceServer
// for forward compatibility.
//
// FiatService defines the balance service.
type FiatServiceServer interface {
	AddBalanceByAdmin(context.Context, *BalanceAdjustmentRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFiatServiceServer()
}

// UnimplementedFiatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFiatServiceServer struct{}

func (UnimplementedFiatServiceServer) AddBalanceByAdmin(context.Context, *BalanceAdjustmentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBalanceByAdmin not implemented")
}
func (UnimplementedFiatServiceServer) mustEmbedUnimplementedFiatServiceServer() {}
func (UnimplementedFiatServiceServer) testEmbeddedByValue()                     {}

// UnsafeFiatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FiatServiceServer will
// result in compilation errors.
type UnsafeFiatServiceServer interface {
	mustEmbedUnimplementedFiatServiceServer()
}

func RegisterFiatServiceServer(s grpc.ServiceRegistrar, srv FiatServiceServer) {
	// If the following call pancis, it indicates UnimplementedFiatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FiatService_ServiceDesc, srv)
}

func _FiatService_AddBalanceByAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiatServiceServer).AddBalanceByAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiatService_AddBalanceByAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiatServiceServer).AddBalanceByAdmin(ctx, req.(*BalanceAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FiatService_ServiceDesc is the grpc.ServiceDesc for FiatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FiatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foundationtoken.FiatService",
	HandlerType: (*FiatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBalanceByAdmin",
			Handler:    _FiatService_AddBalanceByAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balance_service.proto",
}
